---
:backgroundrb:
  :ip: 127.0.0.1
  :environment: development
  :port: 2000
:schedules:
  :department_creating_worker:
    :create:
      :trigger_args: "* * * * * * *"
  :date_time_worker:
    :create:
      :trigger_args: 10 * * * * * *
